name: eq-chess
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - sqlalchemy>=2.0.0
    - tqdm>=4.65.0
    - psycopg2-binary
    - python-dotenv
    - matplotlib
    - git+https://github.com/robertstrauss/jupytermosaic
    - pytorch-lightning
    - wandb
    - python-chess
